/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i2 from './hint.component';
export declare const RenderType_HintComponent: i0.RendererType2;
export declare function View_HintComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_HintComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const HintComponentNgFactory: i0.ComponentFactory<i2.HintComponent>;
