/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['body {\n  padding: 25px;\n  background-color: #fff;\n  position: relative;\n}\n'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2thaXNodXUwMTIzL3dvcmsvYW5ndWxhci1jdXN0b20tdG91ci9zZXJ2ZXIvYXBwL3N0eWxlLmNzcy5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMva2Fpc2h1dTAxMjMvd29yay9hbmd1bGFyLWN1c3RvbS10b3VyL3NlcnZlci9hcHAvc3R5bGUuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
