"use strict";
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.styles = ['body {\n  padding: 25px;\n  background-color: #fff;\n  position: relative;\n}\n'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2thaXNodXUwMTIzL3RtcC9hbmd1bGFyLWN1c3RvbS10b3VyL3NlcnZlci9hcHAvc3R5bGUuY3NzLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9rYWlzaHV1MDEyMy90bXAvYW5ndWxhci1jdXN0b20tdG91ci9zZXJ2ZXIvYXBwL3N0eWxlLmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
//# sourceMappingURL=style.css.ngstyle.js.map