/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './hint.component';
import * as i3 from './hint.service';
const styles_HintComponent:any[] = ([] as any[]);
export const RenderType_HintComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HintComponent,data:{}});
function View_HintComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),0,'div',[['class',
      'hint-overlay']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:any = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.dismiss()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any)))],(null as any),(null as any));
}
export function View_HintComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_HintComponent_1)),i0.ɵdid(1,16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,
      i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any))],(_ck,_v) => {
    var _co:i2.HintComponent = _v.component;
    const currVal_0:any = _co.show;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_HintComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'tour-overlay',
      ([] as any[]),(null as any),(null as any),(null as any),View_HintComponent_0,
      RenderType_HintComponent)),i0.ɵdid(1,49152,(null as any),0,i2.HintComponent,
      [i3.HintService],(null as any),(null as any))],(null as any),(null as any));
}
export const HintComponentNgFactory:i0.ComponentFactory<i2.HintComponent> = i0.ɵccf('tour-overlay',
    i2.HintComponent,View_HintComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2thaXNodXUwMTIzL3dvcmsvYW5ndWxhci1jdXN0b20tdG91ci9zcmMvaGludC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMva2Fpc2h1dTAxMjMvd29yay9hbmd1bGFyLWN1c3RvbS10b3VyL3NyYy9oaW50LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2thaXNodXUwMTIzL3dvcmsvYW5ndWxhci1jdXN0b20tdG91ci9zcmMvaGludC5jb21wb25lbnQudHMuSGludENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMva2Fpc2h1dTAxMjMvd29yay9hbmd1bGFyLWN1c3RvbS10b3VyL3NyYy9oaW50LmNvbXBvbmVudC50cy5IaW50Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImhpbnQtb3ZlcmxheVwiICpuZ0lmPVwic2hvd1wiIChjbGljayk9XCJkaXNtaXNzKClcIj48L2Rpdj4iLCI8dG91ci1vdmVybGF5PjwvdG91ci1vdmVybGF5PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtJQUFBO0lBQUE7SUFBdUM7TUFBQTtNQUFBO0lBQUE7SUFBdkM7RUFBQTs7O29CQUFBO01BQUEsOEJBQUE7b0JBQUE7O0lBQTBCO0lBQTFCLFdBQTBCLFNBQTFCOzs7O29CQ0FBO01BQUE7OEJBQUEsVUFBQTtNQUFBOzs7In0=
